version: '3.3'
services:
    rabbitmq:
        container_name: amqp
        environment:
            - RABBITMQ_DEFAULT_USER=user
            - RABBITMQ_DEFAULT_PASS=password
        ports:
            - '15672:15672'
            - '5672:5672'
        image: 'rabbitmq:3-management-alpine'